version: '3'

services:
  quiz-app-react-dev:
    container_name: quiz-app-react-dev
    build:
      context: ..
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true