version: '3'

services:
  quiz-app-react:
    container_name: quiz-app-react
    build:
      context: ..
      dockerfile: Dockerfile.prod
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 1337:80
    stdin_open: true