export const QUESTION_STYLES = [
    { value: '', label: '' },
    { value: 'multipleChoice', label: 'Multiple Choice' },
    { value: 'multipleSelection', label: 'Multiple Selection' }
];

export const DIFFICULTY = [
    { value: '', label: '' },
    { value: 'Gimme', label: 'Gimme' },
    { value: 'Easy', label: 'Easy' },
    { value: 'Medium', label: 'Medium' },
    { value: 'Hard', label: 'Hard' },
    { value: 'Very Hard', label: 'Very Hard' },
];

export const QUESTION_CATEGORIES = [
    {value: "General", label: "General"},
    {value: "Portal Pages", label: "Portal Pages"},
    {value: "Feeds", label: "Feeds"},
    {value: "DB", label: "DB"},
    {value: "Health Check", label: "Health Check"},
    {value: "Process Models", label: "Process Models"},
    {value: "Data Stores", label: "Data Stores"},
    {value: "Records", label: "Records"},
    {value: "Expressions", label: "Expressions"},
    {value: "Miscellaneous", label: "Miscellaneous"},
    {value: "Security", label: "Security"},
    {value: "Actions", label: "Actions"},
    {value: "Activity Chaining", label: "Activity Chaining"},
    {value: "Arrays", label: "Arrays"},
    {value: "Best Practice", label: "Best Practice"},
    {value: "CDT", label: "CDT"},
    {value: "Data Structure", label: "Data Structure"},
    {value: "Design", label: "Design"},
    {value: "Escalation", label: "Escalation"},
    {value: "Event", label: "Event"},
    {value: "Export", label: "Export"},
    {value: "Expressions", label: "Expressions"},
    {value: "Filter", label: "Filter"},
    {value: "JPA", label: "JPA"},
    {value: "Logic", label: "Logic"},
    {value: "Message", label: "Message"},
    {value: "Messaging", label: "Messaging"},
    {value: "Pages", label: "Pages"},
    {value: "Query", label: "Query"},
    {value: "Query Rule", label: "Query Rule"},
    {value: "Quick Task", label: "Quick Task"},
    {value: "Race Condition", label: "Race Condition"},
    {value: "Report", label: "Report"},
    {value: "Security", label: "Security"},
    {value: "Smart Services", label: "Smart Services"},
    {value: "Start Node", label: "Start Node"},
    {value: "System", label: "System"},
    {value: "Tests", label: "Tests"},
    {value: "Trigger", label: "Trigger"},
    {value: "Views", label: "Views"},
    {value: "XSD", label: "XSD"},
    {value: "Roles", label: "Roles"},
    {value: "Knowledge Centers", label: "Knowledge Centers"},
    {value: "Publishing", label: "Publishing"},
    {value: "News", label: "News"},
    {value: "Tempo Reports", label: "Tempo Reports"},
    {value: "Rules", label: "Rules"},
    {value: "General", label: "General"},
    {value: "Constants", label: "Constants"},
    {value: "Functions", label: "Functions"}
];